name: hork_project
description: The Hork project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  alarm: ^4.1.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.15  # Include this if you need to access the file system
  window_size: ^0.1.0  # 
  process_run: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data.json  # Add your JSON file here